// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package order

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PurchaseOrder struct {
	Productid            string   `protobuf:"bytes,1,opt,name=productid,proto3" json:"productid,omitempty"`
	Productname          string   `protobuf:"bytes,2,opt,name=productname,proto3" json:"productname,omitempty"`
	Cost                 float64  `protobuf:"fixed64,3,opt,name=cost,proto3" json:"cost,omitempty"`
	Quantity             int32    `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PurchaseOrder) Reset()         { *m = PurchaseOrder{} }
func (m *PurchaseOrder) String() string { return proto.CompactTextString(m) }
func (*PurchaseOrder) ProtoMessage()    {}
func (*PurchaseOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *PurchaseOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurchaseOrder.Unmarshal(m, b)
}
func (m *PurchaseOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurchaseOrder.Marshal(b, m, deterministic)
}
func (m *PurchaseOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurchaseOrder.Merge(m, src)
}
func (m *PurchaseOrder) XXX_Size() int {
	return xxx_messageInfo_PurchaseOrder.Size(m)
}
func (m *PurchaseOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_PurchaseOrder.DiscardUnknown(m)
}

var xxx_messageInfo_PurchaseOrder proto.InternalMessageInfo

func (m *PurchaseOrder) GetProductid() string {
	if m != nil {
		return m.Productid
	}
	return ""
}

func (m *PurchaseOrder) GetProductname() string {
	if m != nil {
		return m.Productname
	}
	return ""
}

func (m *PurchaseOrder) GetCost() float64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *PurchaseOrder) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type TotalCost struct {
	Totalcost            float64  `protobuf:"fixed64,1,opt,name=totalcost,proto3" json:"totalcost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalCost) Reset()         { *m = TotalCost{} }
func (m *TotalCost) String() string { return proto.CompactTextString(m) }
func (*TotalCost) ProtoMessage()    {}
func (*TotalCost) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *TotalCost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalCost.Unmarshal(m, b)
}
func (m *TotalCost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalCost.Marshal(b, m, deterministic)
}
func (m *TotalCost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalCost.Merge(m, src)
}
func (m *TotalCost) XXX_Size() int {
	return xxx_messageInfo_TotalCost.Size(m)
}
func (m *TotalCost) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalCost.DiscardUnknown(m)
}

var xxx_messageInfo_TotalCost proto.InternalMessageInfo

func (m *TotalCost) GetTotalcost() float64 {
	if m != nil {
		return m.Totalcost
	}
	return 0
}

type AllPurchase struct {
	Orders               []*PurchaseOrder `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AllPurchase) Reset()         { *m = AllPurchase{} }
func (m *AllPurchase) String() string { return proto.CompactTextString(m) }
func (*AllPurchase) ProtoMessage()    {}
func (*AllPurchase) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *AllPurchase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllPurchase.Unmarshal(m, b)
}
func (m *AllPurchase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllPurchase.Marshal(b, m, deterministic)
}
func (m *AllPurchase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllPurchase.Merge(m, src)
}
func (m *AllPurchase) XXX_Size() int {
	return xxx_messageInfo_AllPurchase.Size(m)
}
func (m *AllPurchase) XXX_DiscardUnknown() {
	xxx_messageInfo_AllPurchase.DiscardUnknown(m)
}

var xxx_messageInfo_AllPurchase proto.InternalMessageInfo

func (m *AllPurchase) GetOrders() []*PurchaseOrder {
	if m != nil {
		return m.Orders
	}
	return nil
}

type SearchValue struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchValue) Reset()         { *m = SearchValue{} }
func (m *SearchValue) String() string { return proto.CompactTextString(m) }
func (*SearchValue) ProtoMessage()    {}
func (*SearchValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *SearchValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchValue.Unmarshal(m, b)
}
func (m *SearchValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchValue.Marshal(b, m, deterministic)
}
func (m *SearchValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchValue.Merge(m, src)
}
func (m *SearchValue) XXX_Size() int {
	return xxx_messageInfo_SearchValue.Size(m)
}
func (m *SearchValue) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchValue.DiscardUnknown(m)
}

var xxx_messageInfo_SearchValue proto.InternalMessageInfo

func (m *SearchValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ResponseMessage struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseMessage) Reset()         { *m = ResponseMessage{} }
func (m *ResponseMessage) String() string { return proto.CompactTextString(m) }
func (*ResponseMessage) ProtoMessage()    {}
func (*ResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{4}
}

func (m *ResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseMessage.Unmarshal(m, b)
}
func (m *ResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseMessage.Marshal(b, m, deterministic)
}
func (m *ResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseMessage.Merge(m, src)
}
func (m *ResponseMessage) XXX_Size() int {
	return xxx_messageInfo_ResponseMessage.Size(m)
}
func (m *ResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseMessage proto.InternalMessageInfo

func (m *ResponseMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type EmptyParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyParams) Reset()         { *m = EmptyParams{} }
func (m *EmptyParams) String() string { return proto.CompactTextString(m) }
func (*EmptyParams) ProtoMessage()    {}
func (*EmptyParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{5}
}

func (m *EmptyParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyParams.Unmarshal(m, b)
}
func (m *EmptyParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyParams.Marshal(b, m, deterministic)
}
func (m *EmptyParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyParams.Merge(m, src)
}
func (m *EmptyParams) XXX_Size() int {
	return xxx_messageInfo_EmptyParams.Size(m)
}
func (m *EmptyParams) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyParams.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyParams proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PurchaseOrder)(nil), "order.PurchaseOrder")
	proto.RegisterType((*TotalCost)(nil), "order.TotalCost")
	proto.RegisterType((*AllPurchase)(nil), "order.AllPurchase")
	proto.RegisterType((*SearchValue)(nil), "order.SearchValue")
	proto.RegisterType((*ResponseMessage)(nil), "order.ResponseMessage")
	proto.RegisterType((*EmptyParams)(nil), "order.EmptyParams")
}

func init() {
	proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077)
}

var fileDescriptor_cd01338c35d87077 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x52, 0xcf, 0x4b, 0xfb, 0x30,
	0x1c, 0x5d, 0xbf, 0xdb, 0xfa, 0xb5, 0x9f, 0x30, 0x84, 0x0f, 0x45, 0x4a, 0xf1, 0x30, 0xe2, 0xc1,
	0x09, 0xb2, 0xc3, 0xa6, 0x27, 0x4f, 0x43, 0xbc, 0x29, 0x8e, 0x4e, 0xbc, 0xc7, 0x36, 0x68, 0xa1,
	0x6d, 0x6a, 0x92, 0x0e, 0x76, 0xf2, 0xdf, 0xf2, 0xcf, 0x33, 0x4d, 0xbb, 0xad, 0x93, 0x79, 0xcb,
	0xfb, 0xd1, 0xbc, 0xf7, 0x42, 0x81, 0x08, 0x99, 0x70, 0x39, 0x2d, 0xa5, 0xd0, 0x02, 0x87, 0x16,
	0xd0, 0x2f, 0x18, 0x2d, 0x2b, 0x19, 0x7f, 0x30, 0xc5, 0x9f, 0x6b, 0x02, 0xcf, 0xc1, 0x33, 0x86,
	0xa4, 0x8a, 0x75, 0x9a, 0x04, 0xce, 0xd8, 0x99, 0x78, 0xd1, 0x9e, 0xc0, 0x31, 0x90, 0x16, 0x14,
	0x2c, 0xe7, 0xc1, 0x3f, 0xab, 0x77, 0x29, 0x44, 0x18, 0xc4, 0x42, 0xe9, 0xa0, 0x6f, 0x24, 0x27,
	0xb2, 0x67, 0x0c, 0xe1, 0xe4, 0xb3, 0x62, 0x85, 0x4e, 0xf5, 0x26, 0x18, 0x18, 0x7e, 0x18, 0xed,
	0x30, 0xbd, 0x02, 0xef, 0x45, 0x68, 0x96, 0xdd, 0xd7, 0x46, 0x13, 0xae, 0x6b, 0x60, 0x6f, 0x70,
	0xec, 0x0d, 0x7b, 0x82, 0xde, 0x01, 0x59, 0x64, 0xd9, 0xb6, 0x2e, 0x5e, 0x83, 0x6b, 0x37, 0x28,
	0xe3, 0xec, 0x4f, 0xc8, 0xcc, 0x9f, 0x36, 0xfb, 0x0e, 0xf6, 0x44, 0xad, 0x87, 0x5e, 0x00, 0x59,
	0x71, 0x66, 0x94, 0x57, 0x96, 0x55, 0x1c, 0x7d, 0x18, 0xae, 0xeb, 0x43, 0x3b, 0xb1, 0x01, 0xf4,
	0x12, 0x4e, 0x23, 0xae, 0x4a, 0x51, 0x28, 0xfe, 0xc4, 0x95, 0x62, 0xef, 0x7f, 0x19, 0x47, 0x40,
	0x1e, 0xf2, 0x52, 0x6f, 0x96, 0x4c, 0xb2, 0x5c, 0xcd, 0xbe, 0x1d, 0xf0, 0x0f, 0x62, 0x57, 0x5c,
	0xae, 0xd3, 0x98, 0xe3, 0x0d, 0xb8, 0x4d, 0x2a, 0x62, 0xdb, 0xae, 0x53, 0x22, 0x3c, 0xda, 0x98,
	0xf6, 0xf0, 0x16, 0xfa, 0x8b, 0x24, 0xc1, 0xa3, 0x72, 0x78, 0xd6, 0xb2, 0xbf, 0x8a, 0x9a, 0xcf,
	0xe6, 0xf0, 0xff, 0x31, 0x55, 0xda, 0xbc, 0xd1, 0x2e, 0xad, 0x53, 0x32, 0xdc, 0x72, 0x9d, 0x37,
	0xa4, 0xbd, 0x37, 0xd7, 0xfe, 0x0e, 0xf3, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x14, 0xe0, 0x14,
	0x02, 0x1d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PurchaseOrderServiceClient is the client API for PurchaseOrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PurchaseOrderServiceClient interface {
	Search(ctx context.Context, in *SearchValue, opts ...grpc.CallOption) (*PurchaseOrder, error)
	Add(ctx context.Context, in *PurchaseOrder, opts ...grpc.CallOption) (*ResponseMessage, error)
	ListAll(ctx context.Context, in *EmptyParams, opts ...grpc.CallOption) (*AllPurchase, error)
}

type purchaseOrderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPurchaseOrderServiceClient(cc grpc.ClientConnInterface) PurchaseOrderServiceClient {
	return &purchaseOrderServiceClient{cc}
}

func (c *purchaseOrderServiceClient) Search(ctx context.Context, in *SearchValue, opts ...grpc.CallOption) (*PurchaseOrder, error) {
	out := new(PurchaseOrder)
	err := c.cc.Invoke(ctx, "/order.PurchaseOrderService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseOrderServiceClient) Add(ctx context.Context, in *PurchaseOrder, opts ...grpc.CallOption) (*ResponseMessage, error) {
	out := new(ResponseMessage)
	err := c.cc.Invoke(ctx, "/order.PurchaseOrderService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseOrderServiceClient) ListAll(ctx context.Context, in *EmptyParams, opts ...grpc.CallOption) (*AllPurchase, error) {
	out := new(AllPurchase)
	err := c.cc.Invoke(ctx, "/order.PurchaseOrderService/ListAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PurchaseOrderServiceServer is the server API for PurchaseOrderService service.
type PurchaseOrderServiceServer interface {
	Search(context.Context, *SearchValue) (*PurchaseOrder, error)
	Add(context.Context, *PurchaseOrder) (*ResponseMessage, error)
	ListAll(context.Context, *EmptyParams) (*AllPurchase, error)
}

// UnimplementedPurchaseOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPurchaseOrderServiceServer struct {
}

func (*UnimplementedPurchaseOrderServiceServer) Search(ctx context.Context, req *SearchValue) (*PurchaseOrder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedPurchaseOrderServiceServer) Add(ctx context.Context, req *PurchaseOrder) (*ResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedPurchaseOrderServiceServer) ListAll(ctx context.Context, req *EmptyParams) (*AllPurchase, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAll not implemented")
}

func RegisterPurchaseOrderServiceServer(s *grpc.Server, srv PurchaseOrderServiceServer) {
	s.RegisterService(&_PurchaseOrderService_serviceDesc, srv)
}

func _PurchaseOrderService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseOrderServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.PurchaseOrderService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseOrderServiceServer).Search(ctx, req.(*SearchValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseOrderService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseOrderServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.PurchaseOrderService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseOrderServiceServer).Add(ctx, req.(*PurchaseOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseOrderService_ListAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseOrderServiceServer).ListAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.PurchaseOrderService/ListAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseOrderServiceServer).ListAll(ctx, req.(*EmptyParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _PurchaseOrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.PurchaseOrderService",
	HandlerType: (*PurchaseOrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _PurchaseOrderService_Search_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _PurchaseOrderService_Add_Handler,
		},
		{
			MethodName: "ListAll",
			Handler:    _PurchaseOrderService_ListAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
